### ISSUE TITLE
Authentication failing

### ISSUE THREAD

**Issue by DrawTR** [FreshSupaSulley/DuOSU#4]
Hey, I'm getting the following error:

```"Duo denied handling request at /push/v2/device/transactions (was the device deleted?)"```

...even when readding the 'Android' device. Is there any fix to this? Is this Duo blocking the device?

**Comment by FreshSupaSulley** [comment]
Interesting. I've had issues where that endpoint wasn't working for a short time, but then it randomly started working again. What organization that's protected by Duo are you trying to access with this extension? I've only been able to test this extension with Ohio State.

Not sure if you have a lot of experience with web dev, but thought I would include this anyways: If the error is still happening, right click anywhere on the DuOSU popup page, hit Inspect, then navigate the network tab to start recording the network activity. Then, try to login through Duo again with DuOSU. You can still click on the "Try Again" button while the inspector window is open. That should give you details about what is going wrong. The console might through useful info as well.

**Comment by DrawTR** [comment]
Ah, sorry for the worry -- like you said, that endpoint seemed to abruptly came back on again. Worth nothing that I did try readding the device, so it was probably some backend issue. Thank you!

**Comment by FreshSupaSulley** [comment]
All good! I appreciate you taking the time to open the issue anyway. Let me know if it becomes reoccurring.
